/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEarnRouteImport } from './routes/_authenticated/earn'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as ApiPublicPostbackProviderRouteImport } from './routes/api/public/postback/$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarnRoute = AuthenticatedEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPostbackProviderRoute =
  ApiPublicPostbackProviderRouteImport.update({
    id: '/api/public/postback/$provider',
    path: '/api/public/postback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earn': typeof AuthenticatedEarnRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/public/postback/$provider': typeof ApiPublicPostbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earn': typeof AuthenticatedEarnRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/public/postback/$provider': typeof ApiPublicPostbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/earn': typeof AuthenticatedEarnRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/public/postback/$provider': typeof ApiPublicPostbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/earn'
    | '/referrals'
    | '/rewards'
    | '/support'
    | '/videos'
    | '/withdraw'
    | '/api/public/postback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/earn'
    | '/referrals'
    | '/rewards'
    | '/support'
    | '/videos'
    | '/withdraw'
    | '/api/public/postback/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/earn'
    | '/_authenticated/referrals'
    | '/_authenticated/rewards'
    | '/_authenticated/support'
    | '/_authenticated/videos'
    | '/_authenticated/withdraw'
    | '/api/public/postback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicPostbackProviderRoute: typeof ApiPublicPostbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earn': {
      id: '/_authenticated/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof AuthenticatedEarnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/postback/$provider': {
      id: '/api/public/postback/$provider'
      path: '/api/public/postback/$provider'
      fullPath: '/api/public/postback/$provider'
      preLoaderRoute: typeof ApiPublicPostbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEarnRoute: typeof AuthenticatedEarnRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEarnRoute: AuthenticatedEarnRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicPostbackProviderRoute: ApiPublicPostbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
