/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSurveysRouteImport } from './routes/_authenticated/surveys'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as ApiPublicPostbackProviderRouteImport } from './routes/api/public/postback/$provider'
import { Route as ApiPublicPostbackCpxResearchRouteImport } from './routes/api/public/postback/cpx-research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSurveysRoute = AuthenticatedSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPostbackProviderRoute =
  ApiPublicPostbackProviderRouteImport.update({
    id: '/api/public/postback/$provider',
    path: '/api/public/postback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostbackCpxResearchRoute =
  ApiPublicPostbackCpxResearchRouteImport.update({
    id: '/api/public/postback/cpx-research',
    path: '/api/public/postback/cpx-research',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/surveys': typeof AuthenticatedSurveysRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/public/postback/$provider': typeof ApiPublicPostbackProviderRoute
  '/api/public/postback/cpx-research': typeof ApiPublicPostbackCpxResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/surveys': typeof AuthenticatedSurveysRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/public/postback/$provider': typeof ApiPublicPostbackProviderRoute
  '/api/public/postback/cpx-research': typeof ApiPublicPostbackCpxResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/surveys': typeof AuthenticatedSurveysRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/public/postback/$provider': typeof ApiPublicPostbackProviderRoute
  '/api/public/postback/cpx-research': typeof ApiPublicPostbackCpxResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/rewards'
    | '/support'
    | '/surveys'
    | '/videos'
    | '/withdraw'
    | '/api/public/postback/$provider'
    | '/api/public/postback/cpx-research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/rewards'
    | '/support'
    | '/surveys'
    | '/videos'
    | '/withdraw'
    | '/api/public/postback/$provider'
    | '/api/public/postback/cpx-research'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/rewards'
    | '/_authenticated/support'
    | '/_authenticated/surveys'
    | '/_authenticated/videos'
    | '/_authenticated/withdraw'
    | '/api/public/postback/$provider'
    | '/api/public/postback/cpx-research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicPostbackProviderRoute: typeof ApiPublicPostbackProviderRoute
  ApiPublicPostbackCpxResearchRoute: typeof ApiPublicPostbackCpxResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/surveys': {
      id: '/_authenticated/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof AuthenticatedSurveysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/postback/$provider': {
      id: '/api/public/postback/$provider'
      path: '/api/public/postback/$provider'
      fullPath: '/api/public/postback/$provider'
      preLoaderRoute: typeof ApiPublicPostbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/postback/cpx-research': {
      id: '/api/public/postback/cpx-research'
      path: '/api/public/postback/cpx-research'
      fullPath: '/api/public/postback/cpx-research'
      preLoaderRoute: typeof ApiPublicPostbackCpxResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedSurveysRoute: typeof AuthenticatedSurveysRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedSurveysRoute: AuthenticatedSurveysRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicPostbackProviderRoute: ApiPublicPostbackProviderRoute,
  ApiPublicPostbackCpxResearchRoute: ApiPublicPostbackCpxResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
